version: "3.9"
services:
  web:
    build: .
    container_name: xss_teste_web
    ports:
      - "3000:3000"
    environment:
      # Local testing: forward your env vars to the container
      UPSTASH_REDIS_REST_URL: ${UPSTASH_REDIS_REST_URL}
      UPSTASH_REDIS_REST_TOKEN: ${UPSTASH_REDIS_REST_TOKEN}
      NODE_ENV: production
      PORT: 3000